# Generated by Django 4.2.2 on 2023-06-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('postDate', models.DateTimeField()),
                ('postBody', models.CharField(max_length=255)),
                ('alreadyRead', models.CharField(default='FALSE', max_length=255)),
                ('wordNotification', models.CharField(default='FALSE', max_length=255)),
                ('postUrl', models.URLField(null=True)),
                ('userUrl', models.URLField(null=True)),
                ('otherUrl', models.URLField(null=True)),
                ('searchPlace', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
